/**
 * Auto-generated plugin loader
 * DO NOT EDIT - This file is auto-generated by scripts/generate-plugins.js
 * Run: npm run generate:plugins
 */

import "./ai/cici";
import "./ai/gemini";
import "./ai/perplexity";
import "./ai/public";
import "./download/blibli";
import "./download/capcut";
import "./download/facebook";
import "./download/igram";
import "./download/instagram";
import "./download/pinterest";
import "./download/spotify";
import "./download/tiktok";
import "./download/twitter";
import "./download/youtube";
import "./download/youtube2";
import "./stalker/instagram";
import "./stalker/tiktok";
import "./stalker/twitter";
