const fs = require("fs");
const path = require("path");

const PLUGINS_DIR = path.join(__dirname, "../lib/plugins");
const OUTPUT_FILE = path.join(PLUGINS_DIR, "index.ts");

function getPluginFiles(dir, baseDir = "") {
  const files = [];
  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const relativePath = baseDir ? `${baseDir}/${item}` : item;
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory() && item !== "utils") {
      files.push(...getPluginFiles(fullPath, relativePath));
    } else if (
      stat.isFile() &&
      item.endsWith(".ts") &&
      item !== "index.ts"
    ) {
      files.push(relativePath.replace(".ts", ""));
    }
  }

  return files;
}

function generatePluginIndex() {
  console.log("🔌 Scanning plugins...");

  const plugins = getPluginFiles(PLUGINS_DIR);

  const imports = plugins
    .map((plugin) => `import "./${plugin}";`)
    .join("\n");

  const content = `/**
 * Auto-generated plugin loader
 * DO NOT EDIT - This file is auto-generated by scripts/generate-plugins.js
 * Run: npm run generate:plugins
 */

${imports}
`;

  fs.writeFileSync(OUTPUT_FILE, content);

  console.log(`✅ Generated ${plugins.length} plugin imports:`);
  plugins.forEach((p) => console.log(`   - ${p}`));
}

generatePluginIndex();
